# Generated by Django 3.1.4 on 2020-12-27 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BakeryItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Bakery_Item_Name', models.CharField(max_length=100)),
                ('IngredientComposition', models.JSONField(default=dict)),
                ('Item_quantity', models.IntegerField()),
                ('Cost_price', models.FloatField()),
                ('Sell_price', models.FloatField()),
                ('Sold_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientListModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Ingredient_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientInventoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Quantity', models.FloatField()),
                ('QuantityUnit', models.CharField(choices=[('Ltr', 'Ltr'), ('Kg', 'Kg'), ('Dozen', 'Dozen'), ('Piece', 'Piece')], max_length=20)),
                ('price', models.FloatField()),
                ('UnitInPricePerUnit', models.CharField(choices=[('Ltr', 'Ltr'), ('Kg', 'Kg'), ('Dozen', 'Dozen'), ('Piece', 'Piece')], max_length=20)),
                ('Ingredient_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='bakeryadmin.ingredientlistmodel')),
            ],
        ),
    ]
